[[pages]]
name = "Ğ’Ğ²ĞµĞ´ĞµĞ½Ğ¸Ğµ Ğ² ĞĞ±ÑƒÑ‡Ğ°ÑÑ‰ÑƒÑ ÑĞ¸ÑÑ‚ĞµĞ¼Ñƒ"
path = "pages/page1.py"

[[pages]]
name = "Dataset"
icon = "ğŸ—‚"
path = "pages/page2.py"

[[pages]]
name = "Dataframe"
icon = "ğŸ“‹"
path = "pages/page3.py"

[[pages]]
name = "Exploratory Data"
icon = "ğŸ“Š"
path = "pages/page4.py"

[[pages]]
name = "Feature Engineering"
icon = "âš™ï¸"
path = "pages/page5.py"

[[pages]]
name = "Pipeline"
icon = "ğŸª¢"
path = "pages/page6.py"

[[pages]]
name = "Model Building"
icon = "ğŸ¤–"
path = "pages/page7.py"

[[pages]]
name = "EDA-ML Reports"
icon = "ğŸ“„"
path = "pages/page8.py"

[[pages]]
name = "Clinical Reports"
icon = "ğŸ“œ"
path = "pages/page9.py"

[[pages]]
name = "Scientific Reports"
icon = "ğŸ“"
path = "pages/page10.py"

[[pages]]
name = "Statistics Samples"
icon = "ğŸ¯"
path = "pages/page11.py"

[[pages]]
name = "ML Samples"
icon = "ğŸ¯"
path = "pages/page12.py"

[[pages]]
name = "User private codes"
icon = "ğŸ¯"
path = "pages/page13.py"